namespace Objects.Items
{
    public enum ItemEnum
    {
        Unset = 0,
        Accelerator = 1,
        Armor = 2,
        BloodThornScarf = 3,
        BruteForce = 4,
        CritDamage = 5,
        CritRate = 6,
        CrownOfThorns = 7,
        Curse = 8,
        CursedThorn = 9,
        Dash = 10,
        Duplicator = 11,
        Duration = 12,
        ComsicAffinity = 13,
        EarthAffinity = 14,
        FireAffinity = 15,
        IceAffinity = 16,
        LightAffinity = 17,
        LightningAffinity = 18,
        WindAffinity = 19,
        ElementalReactionEffect = 20,
        Enlargement = 21,
        FuA = 22,
        LastingPoison = 23,
        Luck = 24,
        Magnet = 25,
        Power = 26,
        Quicken = 27,
        RapidInfliction = 28,
        Rapidity = 29,
        Regeneration = 30,
        ResPen = 31,
        Salvage = 32,
        SecondWind = 33,
        ShinyNecklace = 34,
        Stamina = 35,
        Vitality = 36,
        Vitality2 = 37,
        Wisdom = 38,
    }
}