namespace Objects.Enemies
{
    public enum EnemyTypeEnum
    {
        Abomination1 = 0,
        Abomination2 = 1,
        DarkPunisher = 2,
        Demon = 3,
        DemonGoblin = 4,
        DemonLord = 5,
        DemonBat = 6,
        ElementalBird = 7,
        FireElemental = 8,
        Goblin = 9,
        Golem = 10,
        Kobolt = 11,
        LivingMud = 12,
        OrcBoss = 13,
        PeaceEnder = 14,
        Plant1 = 15,
        Plant2 = 16,
        ShadowElemental = 17,
        ShadowMan = 18,
        Slime = 19,
        SpiralMeat = 20,
        Zombie = 21,
        DemonBoss = 22,
        DemonLordBoss = 23,
        Plant1Boss = 24,
        DarkPunisherBoss = 25,
        Abomination3 = 26,
        BigHead = 27,
        BurningSinner = 28,
        DemonLizard = 29,
        DungeonCrawler = 30,
        FloatingAlien = 31,
        LesserOcti = 32,
        MeltedDemon = 33,
        StoneDemon = 34,
        StoneLizard = 35,
        ToothShroom = 36,
        TurtleOcti = 37,
        Sludge = 38,
        TheWatcher = 39,
        Hellborn = 40,
        InfernoEye = 41,
        HopGoblin = 42,
        FlameDig = 43,
        FirstFlame = 44,
        LizardBrute = 45
    }
}